<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/pekochan/work/portfolio-2024/static/models/ring.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Circle: THREE.Mesh
      Circle001: THREE.Mesh
      Circle002: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/models/ring.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Circle.geometry} material={gltf.nodes.Circle.material} scale={15.47} />
    <T.Mesh geometry={gltf.nodes.Circle001.geometry} material={gltf.nodes.Circle001.material} scale={20.74} />
    <T.Mesh geometry={gltf.nodes.Circle002.geometry} material={gltf.nodes.Circle002.material} scale={16.97} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
